export const GUACAMAYA_FACTS = [
  "La guacamaya bandera (Ara macao) lleva los colores de Venezuela: amarillo, azul y rojo.",
  "En Venezuela las llamamos guacamayas. En otros países suelen decirles guacamayos.",
  "Viven en pareja casi toda la vida y suelen volar juntas, una al lado de la otra.",
  "Su pico puede partir semillas durísimas, incluso nueces de palma.",
  "Pueden vivir más de 50 años. Algunas llegan a los 60 o 70.",
  "El azul de sus plumas no es pigmento: es un truco de luz en la estructura de la pluma.",
  "En los Llanos y el sur de Venezuela se las ve en bandadas ruidosas al atardecer.",
  "Anidan en huecos de árboles altos. Vuelven al mismo nido año tras año.",
  "Comen arcilla en barrancos para neutralizar toxinas de semillas y frutos.",
  "Su grito se oye a kilómetros. Así se encuentran entre la selva densa.",
  "La guacamaya militar (Ara militaris) aún sobrevive en zonas de Venezuela, pero está amenazada.",
  "Tienen patas zigodáctilas: dos dedos adelante y dos atrás, perfectas para trepar.",
  "Pueden volar a más de 50 km/h y cruzar ríos y sabanas en línea recta.",
  "El rojo de sus plumas sí viene de pigmentos, a menudo ligados a la dieta.",
  "Aprenden sonidos de su grupo. En libertad imitan llamadas, no tanto el habla humana.",
  "En Amazonas y Bolívar conviven varias especies: bandera, azul y amarilla, y verde.",
  "Un pico desgastado les crece toda la vida, como las uñas.",
  "Son de las aves más sociables del trópico: duermen, comen y viajan en familia.",
  "La guacamaya azul y amarilla (Ara ararauna) recorre galerías de moriche en los Llanos.",
  "La guacamaya verde o choclera (Ara severus) es más chica y muy común en bosques ribereños.",
  "La guacamaya roja y verde (Ara chloropterus) también habita el sur venezolano.",
  "En Canaima y el Escudo Guayanés se las ve sobre tepuyes y ríos de aguas negras.",
  "El Parque Nacional Cinaruco-Capanaparo es un buen lugar para verlas en los Llanos.",
  "En Delta Amacuro usan los grandes palmares como comedor y dormidero.",
  "En la Sierra de Perijá quedan grupos de guacamaya militar, muy sensibles a la tala.",
  "En Barinas y Portuguesa todavía cruzan palmares al amanecer, en parejas.",
  "En el Amazonas venezolano anidan en ceibas, mijaoes y otros árboles emergentes.",
  "En Bolívar siguen rutas de frutas: cuando madura una palma, llega la bandada.",
  "Caracas las volvió símbolo de color, pero su casa real es la selva y el llano.",
  "Muchas guacamayas venezolanas bajan a salados o barrancos de arcilla en la estación seca.",
  "Prefieren dormir en palmas altas: desde ahí vigilan jaguares, harpy eagles y gente.",
  "Un dormidero de 50 aves puede oírse antes de verse: es un coro naranja y azul.",
  "Cuando una pareja vuela, casi siempre va la hembra un poco más atrás o al lado.",
  "Se acicalan mutuamente la cabeza, donde no llegan con el pico.",
  "Si pierde a su pareja, a veces se queda sola años. No todas vuelven a emparejarse.",
  "El cortejo incluye comida: el macho le pasa pulpa de fruta pico a pico.",
  "Ponen de 2 a 4 huevos, pero a menudo solo sobrevive un pichón.",
  "Incuban unos 25 a 28 días. El macho trae comida y defiende el hueco.",
  "Los pichones tardan 3 meses en volar y meses más en independizarse.",
  "Un hueco de nido bueno se hereda: varias generaciones pueden usarlo.",
  "Compiten por nidos con tucanes, loros, abejas y a veces con otras guacamayas.",
  "Si el árbol cae, la pareja busca otro hueco en el mismo territorio.",
  "No construyen nido de palitos: eligen cavidades y las limpian con el pico.",
  "Los juveniles tienen el iris más oscuro; en adultos se aclara con los años.",
  "La piel blanca de la cara muestra líneas de plumas finas, únicas en cada ave.",
  "Esa cara desnuda ayuda a no ensuciarse tanto al comer frutas pegajosas.",
  "La lengua es muscular y áspera: sostiene el alimento mientras el pico lo parte.",
  "El pico superior está articulado y se mueve, no es un casco fijo.",
  "Usan el pico como tercera pata para trepar ramas verticales.",
  "Una mandíbula de guacamaya puede ejercer una fuerza enorme para su tamaño.",
  "Las plumas de vuelo (remeras) son largas y rígidas: planean entre claros del bosque.",
  "La cola larga les da timón: cambian de dirección en un instante entre palmas.",
  "Al aterrizar frenan con las alas abiertas y agarran con las uñas de un golpe.",
  "Mudan plumas poco a poco, nunca todas a la vez, para no perder el vuelo.",
  "El verde oliva de la militar las camufla entre dosel de selva seca.",
  "La bandera destaca a propósito: en pareja, el color dice “aquí estamos”.",
  "El amarillo de la ararauna brilla más al sol de sabana que bajo dosel cerrado.",
  "Las plumas cubiertas de polvo fino (plumas de polvo) mantienen el plumaje seco.",
  "Se bañan en lluvia o en charcos poco profundos, con las alas abiertas.",
  "Después del baño se secan al sol, como si hicieran yoga en una rama.",
  "Comen frutas, semillas, flores, brotes y a veces insectos larvarios.",
  "Les encantan los frutos de palma: moriche, seje, cucurito y corozo.",
  "También picotean mango, jobo, guamo, cacao silvestre y almendro de río.",
  "Tiran mucha comida al suelo: monos y pecaríes aprovechan lo que cae.",
  "Así dispersan semillas a kilómetros de distancia, sembran el bosque al volar.",
  "Algunas semillas solo germinan bien después de pasar por su pico o su paso.",
  "En temporada de mango silvestre, las bandadas se concentran en pocos árboles.",
  "Beben agua de bromelias, huecos de rama y orillas de caño, no solo de ríos grandes.",
  "El pico se desgasta comiendo; si no lo usan, crece de más y les estorba.",
  "Tienen un olfato discreto y una vista excelente, sobre todo para el color.",
  "Ven más matices que el ojo humano: les ayuda a elegir frutos maduros.",
  "El oído fino detecta a la pareja entre el ruido de cigarras y ranas.",
  "Cada bandada tiene “acento”: llamadas que cambian un poco entre regiones.",
  "Los pichones aprenden el dialecto local escuchando a los adultos.",
  "Gritan más al amanecer y al atardecer, cuando salen y vuelven al dormidero.",
  "En mediodía caluroso se quedan quietas a la sombra, con el pico entreabierto.",
  "Jadean con la boca abierta para enfriar el cuerpo, como muchos loros.",
  "Aletean despacio en vuelo de crucero y más rápido si hay halcón cerca.",
  "El águila arpía y el halcón peregrino son de sus depredadores aéreos.",
  "En el nido temen a tucanes, mapurites trepadores y humanos con machete.",
  "Si hay peligro, una ave vigila mientras las otras comen en el árbol.",
  "Alarman con un graznido seco y toda la bandada sale en explosión de color.",
  "En el suelo son torpes; por eso casi todo lo hacen en las copas.",
  "Caminan de lado por las ramas, como funambulistas con cola de plumas.",
  "Juegan: se cuelgan boca abajo, se tiran trozos de palma y se persiguen.",
  "Los jóvenes juegan más. Así practican pico, equilibrio y rangos sociales.",
  "Tienen nombres cortos en el grupo: sílabas que identifican a cada individuo.",
  "Estudios con loros cercanos muestran que pueden contar poco y resolver puzzles.",
  "En cautiverio imitan palabras porque buscan contacto social, no porque “hablen”.",
  "Un ave sola en jaula se deprime: está hecha para bandada y selva enorme.",
  "El tráfico ilegal es una de las peores amenazas en Venezuela y el resto del trópico.",
  "Sacar un pichón del nido suele matar a los hermanos y dañar el árbol.",
  "La tala de palmas y ceibas les quita comedor y cuna al mismo tiempo.",
  "Los incendios de sabana en temporada seca les rompen corredores de vuelo.",
  "Áreas protegidas como Parima-Tapirapeco y Caura aún guardan poblaciones buenas.",
  "En los Llanos, hatos que dejan palmares en pie se llenan otra vez de guacamayas.",
  "Si dejas un árbol muerto en pie, a veces se vuelve nido al año siguiente.",
  "La guacamaya jacinta (Anodorhynchus hyacinthinus), de Brasil, es la más grande del mundo.",
  "Mide casi un metro de largo si se cuenta la cola. No vive en Venezuela.",
  "La guacamaya de Spix, azul cobalto, se extinguió en libertad y hoy se reintroduce en Brasil.",
  "Hay unas 19 especies vivas de guacamayas verdaderas en el género Ara y parientes.",
  "La guacamaya de frente roja y la de hombros rojos son más pequeñas y andinas o chaqueñas.",
  "La militar llega hasta México: es la que más al norte vuela de las grandes guacamayas.",
  "En Centroamérica la bandera fue casi borrada de algunas costas por el comercio de mascotas.",
  "Proyectos de nidos artificiales han ayudado a Ara macao en el Pacífico de Costa Rica.",
  "En Perú y Bolivia, los collpas (lamas de arcilla) atraen cientos de guacamayas a la vez.",
  "Esas escenas de collpa son las más famosas en documentales, pero también ocurren en Guayana.",
  "La arcilla les aporta sales y liga toxinas de semillas inmaduras.",
  "Prefieren semillas duras que otros animales no pueden abrir: menos competencia.",
  "Un buche lleno les dura horas; pueden volar lejos antes de digerir todo.",
  "El hígado y el riñón de un loro grande procesan muchos compuestos de plantas.",
  "No todas las especies comen lo mismo: la verde pica más frutos blandos y flores.",
  "La choclera a veces sigue ríos angostos, de caño en caño, como un pasillo verde.",
  "La azul y amarilla aguanta mejor la sabana abierta que la bandera.",
  "La bandera busca bosque más continuo, con palmas y árboles de dosel alto.",
  "En islas de galería, un solo palmar puede alimentar a una pareja todo un mes.",
  "Marcan territorio cerca del nido, no un feudo enorme como las águilas.",
  "Fuera de cría se mezclan especies distintas en el mismo árbol frutal.",
  "Se ha visto a bandera y roja-verde comer juntas sin pelear, si hay fruta de sobra.",
  "Cuando escasea la comida, el pico más grande gana el mejor racimo.",
  "El nombre Ara viene de un llamado indígena que suena a su propio grito.",
  "“Macaw” en inglés quizá venga de lenguas del Caribe o del tupí.",
  "En varias lenguas amazónicas su nombre imita el graznido: raá, ara, guaca.",
  "Guaca-maya suena a su voz: dos sílabas fuertes y una cola larga de eco.",
  "En la cultura pemón y yanomami aparecen como dueñas del color y del fuego del cielo.",
  "Plumas de guacamaya se usaron en coronas y rituales, siempre con respeto y escasez.",
  "Hoy extraer plumas de aves silvestres es ilegal en Venezuela sin permiso.",
  "Ver una bandada cruzar el Orinoco al atardecer es de los vuelos más bonitos del país.",
  "El Orinoco y el Casiquiare conectan cuencas: las aves usan esos corredores verdes.",
  "Algunas se mueven según las crecientes: siguen la fruta que madura con el agua.",
  "En sequía se concentran en caños que no se secan; en lluvia se dispersan.",
  "Pueden recorrer decenas de kilómetros en un solo día de forrajeo.",
  "Duermen siempre cerca de agua, pero no necesariamente sobre el río.",
  "Un palo seco sobre un morichal es su mirador favorito al amanecer.",
  "Al salir del dormidero primero se estiran un ala y una pata, como atletas.",
  "Luego gritan, se sacuden y despegan en grupos de dos, cuatro y ocho.",
  "Vuelan en formación laxa, no en V de patos: cada pareja mantiene su espacio.",
  "Si hay viento de contra, bajan entre palmas y avanzan a saltos de claro.",
  "Las tormentas de llano las pegan al dosel; esperan que pase el vendaval.",
  "El trueno no las espanta tanto como un motor de bongo o una motosierra.",
  "Se acostumbran a hatos tranquilos, pero huyen de pueblos con jaulas a la vista.",
  "Un comedero artificial las hace dependientes y las expone a robos de pichones.",
  "La mejor forma de “ayudarlas” es dejar palmas, huecos y bosque conectado.",
  "Plantar moriche y seje cerca de caños devuelve comida en una década.",
  "Evitar talar árboles con huecos es más útil que fabricar muchas cajas nido.",
  "Las cajas nido sirven en sitios muy degradados, no reemplazan un bosque.",
  "En zoológicos bien llevados se crían para educación, no para vender como lujo.",
  "Comprar una guacamaya “mansa” casi siempre alimenta la cadena de saqueo.",
  "Un ave criada a mano puede gritar sin parar: extraña a su bandada original.",
  "Morder fuerte no es maldad: es lenguaje de loro grande cuando hay estrés.",
  "En libertad casi no se pluman solas; el arranque de plumas es señal de cautiverio.",
  "Necesitan horas de vuelo al día. Una jaula estrecha les atrofia músculos y mente.",
  "El recorte de alas les quita lo que mejor saben hacer: cruzar el paisaje.",
  "Un dato duro: varias especies de guacamayas ya desaparecieron de islas del Caribe.",
  "La guacamaya cubana y otras antillanas se extinguieron tras la colonización.",
  "Por eso cada bandada del sur de Venezuela vale más de lo que parece.",
  "Ara macao está en Apéndice I o II de CITES según población: el comercio internacional está muy limitado.",
  "La militar está catalogada como vulnerable a escala global.",
  "La jacinta pasó de crítico a vulnerable gracias a protección en el Pantanal.",
  "Aun así, ninguna guacamaya grande está “fuera de peligro” si cae el bosque.",
  "Un solo nido saqueado puede borrar la cría de todo un año de una pareja.",
  "Como crían despacio, recuperarse de un golpe toma décadas.",
  "Contar guacamayas al atardecer en un dormidero es un método clásico de censo.",
  "Los investigadores también usan plumas mudadas para ADN sin atrapar al ave.",
  "Anillos y anillas se ponen solo con permiso y en pichones de proyectos serios.",
  "GPS mochila se usa poco: el equipo pesa y el ave es muy inteligente para quitárselo.",
  "Las fotos de nidos a distancia cuentan más que trepar el árbol y asustarlas.",
  "Si ves un nido, lo mejor es irse: el silencio las deja criar.",
  "En Semana Santa algunos palmares se llenan de visitantes; el ruido baja el éxito de cría.",
  "Los drones cerca del nido las hacen saltar y los huevos se enfrían.",
  "Un binocular y paciencia dan mejor espectáculo que acercarse demasiado.",
  "El mejor momento para verlas en los Llanos es justo después de la lluvia ligera de la tarde.",
  "En Amazonas, sigue el sonido: donde hay un raudal y palmas, suele haber una pareja.",
  "Si ves semillas partidas en forma de cuña al pie de una palma, ellas pasaron por ahí.",
  "Las heces de guacamaya son coloridas: traen restos de fruta y a veces arcilla.",
  "Eso también siembra el bosque. Son campesinas aladas del trópico.",
  "Un bosque sin guacamayas pierde un sembrador de palmas a larga distancia.",
  "Por eso protegerlas es proteger morichales, caños y la sombra del llano.",
  "La próxima vez que oigas un graznido largo al atardecer, mira arriba: puede ser una bandera cruzando.",
] as const;
